### PR TITLE
Updated images for PowerToys

### PR DESCRIPTION
**Pull request by niels9001**
@dedavis6797 @crutkas FYI

Addressing e.g. #8181

Updated a couple of (outdated) images and GIFs. Removed unused images.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@niels9001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by crutkas — APPROVED** [review]

**Comment by crutkas** [comment]
GTG

**Comment by GrantMeStrength** [comment]
Closing — this issue references a UWP page (`windows-apps-src/`) that is now maintained in the [windows-uwp](https://github.com/MicrosoftDocs/windows-uwp) repository, not this one. If the issue is still relevant, please re-file it there. Thank you!

**Comment by crutkas** [comment]
@GrantMeStrength this was fixed / merged back in 2021 :)

**Pull request merged**
